import pandas as pd
print("single dimensional")
s = pd.Series([10,20,30,40,50])
print(s)
print( " ")
print("index changing")
m = pd.Series([10,20,30,40],index = ['a','b','c','d'])
print(m)
print(" ")
print("series object from dictionary")
a = pd.Series({'a':10,'b':20,'c':30,'d':40})
print(a)
print(" ")
print("extracting individual elements")
i = pd.Series([1,2,3,4,5,6,7])
print(i[3])
print(i[-4:])
print(" ")
print("mathematical operations")
mo_1 = pd.Series([10,20,30,40,50])
mo_2 = pd.Series([11,22,33,44,55])
print(mo_1 + mo_2)
print(mo_1 - mo_2)
print(mo_1 * mo_2)
a =mo_1/mo_2
print(a)
print("A S M D")
print(" ")
print("pandas dataframes")
df = pd.DataFrame({"name": ["bob","sam",'raj','amar','anrag','ajad','assam'],"marks" :[50,60,30,40,76,55,79]},index = ['a','b','c','d','e','f','g'])
print(df)
print(" ")
ar = df
head_of = ar.head()
print(head_of)
print(" ")
print(ar.tail())
print(" ")
print(ar.shape)
print(" ")
print(ar.describe())
print(" ")
print(ar.iloc[2:])
print(" ")
print(ar.drop('marks',axis = 1))
print(" ")
print(ar.drop('name',axis = 1))
print(" ")

rr = ar.sort_values(by = 'marks')
print(rr)
print(" ")
